version: '3.8'

services:

  web:
    container_name: php-webapp
    build: .
    ports:
      - "80:80"  # Use port 80 directly in productionn
    volumes:
      - .:/var/www
      - ./public:/var/www/html
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
