version: '3.8'

services:

  web:                                # PHP Web Server Container
    container_name: php-webapp        # Name of the container
    build: .                          # Build the dockerfile in the current directory 
    ports:
      - "8080:80"                     # Map host port 8080 to container port 80 (Apache)
    volumes:
      # - ./src:/var/www/html           # Mount local 'src' folder into Apache web root
      - .:/var/www                    # Project root (PHP sees everything)
      - ./public:/var/www/html        # Apache serves only public files
    restart: unless-stopped           # Restart unless you manually stop it
    depends_on:
      - db                            # Wait for the 'db' service to start (listed below) before this one
    environment:                      # Environment variables for use inside your PHP app
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    
  db:                                   # This is the MySQL database container
      image: mysql:8.0                  # Use the official MySQL 8.0 image
      container_name: mysql-ssd-db      # Name the database container
      restart: always                   # Always restart if the container stops
      environment:                      # Environment variables used to set up MySQL
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ssddb
        MYSQL_USER: ssduser
        MYSQL_PASSWORD: ssdpass
      ports:
        - "3308:3306"                   # Map host port 3306 to container port 3306 (MySQL)
      volumes:
        - ./mysql-data:/var/lib/mysql   # Store DB data in project folder
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      command: --default-authentication-plugin=mysql_native_password


  adminer:                              # GUI access like MySQL Workbench, but via web browser. Visit: http://localhost:8081
    image: adminer
    restart: always
    ports:
      - 8081:8080

  splunk: 
    image: splunk/splunk:latest         # Always pull latest Splunk
    container_name: splunk            
    hostname: splunk
    restart: always                     # Restart if container stops
    ports:
      - "8000:8000"                     # Splunk Web UI Port
      - "8088:8088"                     # HEC Port
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
    volumes: 
      - splunk_data:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc

volumes:
  splunk_data: 
    driver: local
  splunk_etc:
    driver: local