# server {
#     listen 80;
#     server_name _;

#     location / {
#         proxy_pass http://web:9000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }


server {
    listen 80;
    server_name groupmates.bounceme.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://web:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
