name: psalm

on:
  push:
    branches:
      - production
  pull_request:

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl
          tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Initialize Psalm (only if config doesn't exist)
        run: |
          if [ ! -f psalm.xml ]; then
            vendor/bin/psalm --init
          fi

      - name: Run Psalm
        run: vendor/bin/psalm --output-format=github
